[package]
name = "dominus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lock_api = "0.4.9"
parking_lot = "0.12.1"
rand = "0.8.4"
